root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/main.go"
  bin = "tmp/main"
  full_bin = "./tmp/main"
  delay = 2000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]

[log]
  time = true
