// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"), field.Int("versions"), field.String("name"), field.String("email").Unique(), field.String("password"), field.Time("created_at").Optional(), field.Uint64("created_by").Optional(), field.Time("updated_at").Optional(), field.Uint64("updated_by").Optional(), field.Time("deleted_at").Optional(), field.Uint64("deleted_by").Optional()}
}
func (User) Edges() []ent.Edge {
	return nil
}
func (User) Annotations() []schema.Annotation {
	return nil
}
