// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"
	dbModel "ichi-go/pkg/db/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, newUser dbModel.User) (int64, error) {
	ret := _mock.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbModel.User) (int64, error)); ok {
		return returnFunc(ctx, newUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbModel.User) int64); ok {
		r0 = returnFunc(ctx, newUser)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dbModel.User) error); ok {
		r1 = returnFunc(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser dbModel.User
func (_e *MockService_Expecter) Create(ctx interface{}, newUser interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, newUser)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, newUser dbModel.User)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbModel.User
		if args[1] != nil {
			arg1 = args[1].(dbModel.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(n int64, err error) *MockService_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, newUser dbModel.User) (int64, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockService
func (_mock *MockService) GetById(ctx context.Context, id uint32) (*dbModel.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *dbModel.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (*dbModel.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) *dbModel.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbModel.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockService_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockService_Expecter) GetById(ctx interface{}, id interface{}) *MockService_GetById_Call {
	return &MockService_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockService_GetById_Call) Run(run func(ctx context.Context, id uint32)) *MockService_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetById_Call) Return(userModel *dbModel.User, err error) *MockService_GetById_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockService_GetById_Call) RunAndReturn(run func(ctx context.Context, id uint32) (*dbModel.User, error)) *MockService_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// SendNotification provides a mock function for the type MockService
func (_mock *MockService) SendNotification(ctx context.Context, user1 dbModel.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for SendNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbModel.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SendNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNotification'
type MockService_SendNotification_Call struct {
	*mock.Call
}

// SendNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 dbModel.User
func (_e *MockService_Expecter) SendNotification(ctx interface{}, user1 interface{}) *MockService_SendNotification_Call {
	return &MockService_SendNotification_Call{Call: _e.mock.On("SendNotification", ctx, user1)}
}

func (_c *MockService_SendNotification_Call) Run(run func(ctx context.Context, user1 dbModel.User)) *MockService_SendNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbModel.User
		if args[1] != nil {
			arg1 = args[1].(dbModel.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SendNotification_Call) Return(err error) *MockService_SendNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SendNotification_Call) RunAndReturn(run func(ctx context.Context, user1 dbModel.User) error) *MockService_SendNotification_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, updateUser dbModel.User) (int64, error) {
	ret := _mock.Called(ctx, updateUser)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbModel.User) (int64, error)); ok {
		return returnFunc(ctx, updateUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbModel.User) int64); ok {
		r0 = returnFunc(ctx, updateUser)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dbModel.User) error); ok {
		r1 = returnFunc(ctx, updateUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - updateUser dbModel.User
func (_e *MockService_Expecter) Update(ctx interface{}, updateUser interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, updateUser)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, updateUser dbModel.User)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbModel.User
		if args[1] != nil {
			arg1 = args[1].(dbModel.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(n int64, err error) *MockService_Update_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, updateUser dbModel.User) (int64, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
