// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rabbitmq

import (
	"context"
	"ichi-go/internal/infra/queue/rabbitmq"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageConsumer creates a new instance of MockMessageConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageConsumer {
	mock := &MockMessageConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageConsumer is an autogenerated mock type for the MessageConsumer type
type MockMessageConsumer struct {
	mock.Mock
}

type MockMessageConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageConsumer) EXPECT() *MockMessageConsumer_Expecter {
	return &MockMessageConsumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMessageConsumer
func (_mock *MockMessageConsumer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageConsumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMessageConsumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMessageConsumer_Expecter) Close() *MockMessageConsumer_Close_Call {
	return &MockMessageConsumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMessageConsumer_Close_Call) Run(run func()) *MockMessageConsumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageConsumer_Close_Call) Return(err error) *MockMessageConsumer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageConsumer_Close_Call) RunAndReturn(run func() error) *MockMessageConsumer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function for the type MockMessageConsumer
func (_mock *MockMessageConsumer) Consume(ctx context.Context, handler rabbitmq.ConsumeFunc) error {
	ret := _mock.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rabbitmq.ConsumeFunc) error); ok {
		r0 = returnFunc(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageConsumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockMessageConsumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - handler rabbitmq.ConsumeFunc
func (_e *MockMessageConsumer_Expecter) Consume(ctx interface{}, handler interface{}) *MockMessageConsumer_Consume_Call {
	return &MockMessageConsumer_Consume_Call{Call: _e.mock.On("Consume", ctx, handler)}
}

func (_c *MockMessageConsumer_Consume_Call) Run(run func(ctx context.Context, handler rabbitmq.ConsumeFunc)) *MockMessageConsumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rabbitmq.ConsumeFunc
		if args[1] != nil {
			arg1 = args[1].(rabbitmq.ConsumeFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageConsumer_Consume_Call) Return(err error) *MockMessageConsumer_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageConsumer_Consume_Call) RunAndReturn(run func(ctx context.Context, handler rabbitmq.ConsumeFunc) error) *MockMessageConsumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}
