// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rabbitmq

import (
	"context"
	"ichi-go/internal/infra/queue/rabbitmq"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageProducer creates a new instance of MockMessageProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageProducer {
	mock := &MockMessageProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageProducer is an autogenerated mock type for the MessageProducer type
type MockMessageProducer struct {
	mock.Mock
}

type MockMessageProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageProducer) EXPECT() *MockMessageProducer_Expecter {
	return &MockMessageProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMessageProducer
func (_mock *MockMessageProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMessageProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMessageProducer_Expecter) Close() *MockMessageProducer_Close_Call {
	return &MockMessageProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMessageProducer_Close_Call) Run(run func()) *MockMessageProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageProducer_Close_Call) Return(err error) *MockMessageProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageProducer_Close_Call) RunAndReturn(run func() error) *MockMessageProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockMessageProducer
func (_mock *MockMessageProducer) Publish(ctx context.Context, routingKey string, message interface{}, opts rabbitmq.PublishOptions) error {
	ret := _mock.Called(ctx, routingKey, message, opts)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, rabbitmq.PublishOptions) error); ok {
		r0 = returnFunc(ctx, routingKey, message, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageProducer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMessageProducer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - routingKey string
//   - message interface{}
//   - opts rabbitmq.PublishOptions
func (_e *MockMessageProducer_Expecter) Publish(ctx interface{}, routingKey interface{}, message interface{}, opts interface{}) *MockMessageProducer_Publish_Call {
	return &MockMessageProducer_Publish_Call{Call: _e.mock.On("Publish", ctx, routingKey, message, opts)}
}

func (_c *MockMessageProducer_Publish_Call) Run(run func(ctx context.Context, routingKey string, message interface{}, opts rabbitmq.PublishOptions)) *MockMessageProducer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 rabbitmq.PublishOptions
		if args[3] != nil {
			arg3 = args[3].(rabbitmq.PublishOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMessageProducer_Publish_Call) Return(err error) *MockMessageProducer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageProducer_Publish_Call) RunAndReturn(run func(ctx context.Context, routingKey string, message interface{}, opts rabbitmq.PublishOptions) error) *MockMessageProducer_Publish_Call {
	_c.Call.Return(run)
	return _c
}
