// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"ichi-go/internal/applications/order/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CreateOrder(ctx context.Context, req dto.CreateOrderRequest) (*dto.OrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *dto.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateOrderRequest) (*dto.OrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateOrderRequest) *dto.OrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateOrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateOrderRequest
func (_e *MockOrderService_Expecter) CreateOrder(ctx interface{}, req interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, req)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, req dto.CreateOrderRequest)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateOrderRequest
		if args[1] != nil {
			arg1 = args[1].(dto.CreateOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(orderResponse *dto.OrderResponse, err error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, req dto.CreateOrderRequest) (*dto.OrderResponse, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessPayment provides a mock function for the type MockOrderService
func (_mock *MockOrderService) ProcessPayment(ctx context.Context, orderID string) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_ProcessPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPayment'
type MockOrderService_ProcessPayment_Call struct {
	*mock.Call
}

// ProcessPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockOrderService_Expecter) ProcessPayment(ctx interface{}, orderID interface{}) *MockOrderService_ProcessPayment_Call {
	return &MockOrderService_ProcessPayment_Call{Call: _e.mock.On("ProcessPayment", ctx, orderID)}
}

func (_c *MockOrderService_ProcessPayment_Call) Run(run func(ctx context.Context, orderID string)) *MockOrderService_ProcessPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_ProcessPayment_Call) Return(err error) *MockOrderService_ProcessPayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_ProcessPayment_Call) RunAndReturn(run func(ctx context.Context, orderID string) error) *MockOrderService_ProcessPayment_Call {
	_c.Call.Return(run)
	return _c
}
