// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	auth "ichi-go/internal/applications/auth/dto"
	user "ichi-go/internal/applications/user/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetUserByEmail provides a mock function for the type MockService
func (_mock *MockService) GetUserByEmail(ctx context.Context, email string) (*user.UserModel, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *user.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.UserModel, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.UserModel); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockService_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockService_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockService_GetUserByEmail_Call {
	return &MockService_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockService_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockService_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetUserByEmail_Call) Return(userModel *user.UserModel, err error) *MockService_GetUserByEmail_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockService_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.UserModel, error)) *MockService_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(ctx context.Context, req auth.LoginRequest) (*auth.LoginResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.LoginResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) (*auth.LoginResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) *auth.LoginResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.LoginRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.LoginRequest
func (_e *MockService_Expecter) Login(ctx interface{}, req interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, req auth.LoginRequest)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(auth.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(loginResponse *auth.LoginResponse, err error) *MockService_Login_Call {
	_c.Call.Return(loginResponse, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(ctx context.Context, req auth.LoginRequest) (*auth.LoginResponse, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function for the type MockService
func (_mock *MockService) Me(ctx context.Context, userId uint64) (*auth.UserInfo, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 *auth.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*auth.UserInfo, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *auth.UserInfo); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockService_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint64
func (_e *MockService_Expecter) Me(ctx interface{}, userId interface{}) *MockService_Me_Call {
	return &MockService_Me_Call{Call: _e.mock.On("Me", ctx, userId)}
}

func (_c *MockService_Me_Call) Run(run func(ctx context.Context, userId uint64)) *MockService_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Me_Call) Return(userInfo *auth.UserInfo, err error) *MockService_Me_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockService_Me_Call) RunAndReturn(run func(ctx context.Context, userId uint64) (*auth.UserInfo, error)) *MockService_Me_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockService
func (_mock *MockService) RefreshToken(ctx context.Context, req auth.RefreshTokenRequest) (*auth.RefreshTokenResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *auth.RefreshTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshTokenRequest) (*auth.RefreshTokenResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshTokenRequest) *auth.RefreshTokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RefreshTokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.RefreshTokenRequest
func (_e *MockService_Expecter) RefreshToken(ctx interface{}, req interface{}) *MockService_RefreshToken_Call {
	return &MockService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req)}
}

func (_c *MockService_RefreshToken_Call) Run(run func(ctx context.Context, req auth.RefreshTokenRequest)) *MockService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RefreshTokenRequest
		if args[1] != nil {
			arg1 = args[1].(auth.RefreshTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RefreshToken_Call) Return(refreshTokenResponse *auth.RefreshTokenResponse, err error) *MockService_RefreshToken_Call {
	_c.Call.Return(refreshTokenResponse, err)
	return _c
}

func (_c *MockService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, req auth.RefreshTokenRequest) (*auth.RefreshTokenResponse, error)) *MockService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockService
func (_mock *MockService) Register(ctx context.Context, req auth.RegisterRequest) (*auth.RegisterResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.RegisterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RegisterRequest) (*auth.RegisterResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RegisterRequest) *auth.RegisterResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RegisterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RegisterRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.RegisterRequest
func (_e *MockService_Expecter) Register(ctx interface{}, req interface{}) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, req auth.RegisterRequest)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(auth.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Register_Call) Return(registerResponse *auth.RegisterResponse, err error) *MockService_Register_Call {
	_c.Call.Return(registerResponse, err)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(ctx context.Context, req auth.RegisterRequest) (*auth.RegisterResponse, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function for the type MockService
func (_mock *MockService) VerifyPassword(hashedPassword string, password string) bool {
	ret := _mock.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hashedPassword, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockService_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - hashedPassword string
//   - password string
func (_e *MockService_Expecter) VerifyPassword(hashedPassword interface{}, password interface{}) *MockService_VerifyPassword_Call {
	return &MockService_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", hashedPassword, password)}
}

func (_c *MockService_VerifyPassword_Call) Run(run func(hashedPassword string, password string)) *MockService_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyPassword_Call) Return(b bool) *MockService_VerifyPassword_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_VerifyPassword_Call) RunAndReturn(run func(hashedPassword string, password string) bool) *MockService_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}
