// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validator

import (
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContextValidator creates a new instance of MockContextValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextValidator {
	mock := &MockContextValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContextValidator is an autogenerated mock type for the ContextValidator type
type MockContextValidator struct {
	mock.Mock
}

type MockContextValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextValidator) EXPECT() *MockContextValidator_Expecter {
	return &MockContextValidator_Expecter{mock: &_m.Mock}
}

// ValidateWithContext provides a mock function for the type MockContextValidator
func (_mock *MockContextValidator) ValidateWithContext(c echo.Context, i interface{}) error {
	ret := _mock.Called(c, i)

	if len(ret) == 0 {
		panic("no return value specified for ValidateWithContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context, interface{}) error); ok {
		r0 = returnFunc(c, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextValidator_ValidateWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateWithContext'
type MockContextValidator_ValidateWithContext_Call struct {
	*mock.Call
}

// ValidateWithContext is a helper method to define mock.On call
//   - c echo.Context
//   - i interface{}
func (_e *MockContextValidator_Expecter) ValidateWithContext(c interface{}, i interface{}) *MockContextValidator_ValidateWithContext_Call {
	return &MockContextValidator_ValidateWithContext_Call{Call: _e.mock.On("ValidateWithContext", c, i)}
}

func (_c *MockContextValidator_ValidateWithContext_Call) Run(run func(c echo.Context, i interface{})) *MockContextValidator_ValidateWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextValidator_ValidateWithContext_Call) Return(err error) *MockContextValidator_ValidateWithContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextValidator_ValidateWithContext_Call) RunAndReturn(run func(c echo.Context, i interface{}) error) *MockContextValidator_ValidateWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateWithLanguage provides a mock function for the type MockContextValidator
func (_mock *MockContextValidator) ValidateWithLanguage(i interface{}, lang string) error {
	ret := _mock.Called(i, lang)

	if len(ret) == 0 {
		panic("no return value specified for ValidateWithLanguage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string) error); ok {
		r0 = returnFunc(i, lang)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextValidator_ValidateWithLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateWithLanguage'
type MockContextValidator_ValidateWithLanguage_Call struct {
	*mock.Call
}

// ValidateWithLanguage is a helper method to define mock.On call
//   - i interface{}
//   - lang string
func (_e *MockContextValidator_Expecter) ValidateWithLanguage(i interface{}, lang interface{}) *MockContextValidator_ValidateWithLanguage_Call {
	return &MockContextValidator_ValidateWithLanguage_Call{Call: _e.mock.On("ValidateWithLanguage", i, lang)}
}

func (_c *MockContextValidator_ValidateWithLanguage_Call) Run(run func(i interface{}, lang string)) *MockContextValidator_ValidateWithLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextValidator_ValidateWithLanguage_Call) Return(err error) *MockContextValidator_ValidateWithLanguage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextValidator_ValidateWithLanguage_Call) RunAndReturn(run func(i interface{}, lang string) error) *MockContextValidator_ValidateWithLanguage_Call {
	_c.Call.Return(run)
	return _c
}
